document.addEventListener('DOMContentLoaded',()=>{const b=document.body,w=document.getElementById('welcome'),f=document.getElementById('welcomeForm'),i=document.getElementById('username');const NAME='etihadName',FAV='etihadFavourites',MATCH='etihadSavedMatches',TODO='etihadTodos';const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const greet=()=>document.querySelectorAll('.greet').forEach(x=>x.textContent=localStorage.getItem(NAME)?'Greetings, '+localStorage.getItem(NAME)+' 💙':'');if(localStorage.getItem(NAME)){greet();w?.remove()}f?.addEventListener('submit',e=>{e.preventDefault();let v=i.value.trim().replace(/\s+/g,' ');if(v){localStorage.setItem(NAME,v);greet();w.remove()}});
const menus=document.querySelectorAll('.menu');menus.forEach(m=>m.onclick=()=>{const n=m.closest('.nav').querySelector('.links');n.classList.toggle('show')});
const theme=document.getElementById('theme');if(localStorage.getItem('theme')==='dark')b.classList.add('dark');theme?.addEventListener('click',()=>{b.classList.toggle('dark');localStorage.setItem('theme',b.classList.contains('dark')?'dark':'light')});
const settings=document.getElementById('settings'),sb=document.getElementById('settingsBtn');sb?.addEventListener('click',()=>settings?.classList.toggle('show'));document.getElementById('reset')?.addEventListener('click',()=>{localStorage.removeItem(NAME);localStorage.removeItem(FAV);localStorage.removeItem(MATCH);location.href='index.html'});
const share=async()=>{if(navigator.share){try{await navigator.share({title:'Etihad Pride',text:'Manchester City fan hub',url:location.href})}catch(e){}}else{try{await navigator.clipboard.writeText(location.href);alert('Link copied.')}catch(e){alert(location.href)}}};document.querySelectorAll('#share,#homeShare').forEach(x=>x.addEventListener('click',share));
const update=()=>{const fav=get(FAV,[]),matches=get(MATCH,[]);document.querySelectorAll('#favCount,#squadFavCount').forEach(x=>x.textContent=fav.length);document.querySelectorAll('#savedMatchCount,#squadSavedCount').forEach(x=>x.textContent=matches.length);const boxes=document.querySelectorAll('.todo');const done=[...boxes].filter(x=>x.checked).length;document.querySelectorAll('#checkCount').forEach(x=>x.textContent=(boxes.length?Math.round(done/boxes.length*100):0)+'%')};
const q=document.getElementById('q');if(q)q.oninput=()=>document.querySelectorAll('[data-q]').forEach(x=>x.style.display=x.dataset.q.includes(q.value.toLowerCase())?'':'none');
const chips=document.querySelectorAll('.chip');chips.forEach(c=>c.onclick=()=>{chips.forEach(x=>x.classList.remove('active'));c.classList.add('active');const type=c.dataset.type,comp=c.dataset.fixture;if(type)document.querySelectorAll('.item').forEach(x=>x.style.display=type==='all'||x.dataset.type===type?'':'none');if(comp)document.querySelectorAll('.fixture').forEach(x=>x.style.display=comp==='all'||x.dataset.comp===comp?'':'none')});
const favButtons=document.querySelectorAll('.star');favButtons.forEach(x=>{const sync=()=>{const a=get(FAV,[]),on=a.includes(x.dataset.name);x.classList.toggle('on',on);x.textContent=on?'★':'☆'};sync();x.onclick=()=>{let a=get(FAV,[]),n=x.dataset.name;a=a.includes(n)?a.filter(v=>v!==n):[...a,n];put(FAV,a);favButtons.forEach(sync);update()}});
const bells=document.querySelectorAll('.bell');bells.forEach(x=>{const sync=()=>{const a=get(MATCH,[]),on=a.includes(x.dataset.match);x.classList.toggle('on',on);x.textContent=on?'★':'☆'};sync();x.onclick=()=>{let a=get(MATCH,[]),n=x.dataset.match;a=a.includes(n)?a.filter(v=>v!==n):[...a,n];put(MATCH,a);bells.forEach(sync);update()}});
const gm=document.getElementById('galleryModal');document.querySelectorAll('.photo').forEach(p=>p.onclick=()=>{gm.classList.add('show');gm.querySelector('img').src=p.dataset.src;gm.querySelector('h3').textContent=p.dataset.title});if(gm){gm.querySelector('.close').onclick=()=>gm.classList.remove('show');gm.onclick=e=>{if(e.target===gm)gm.classList.remove('show')}}
const cm=document.getElementById('chant'),mm=document.getElementById('chantModal');if(cm&&mm){cm.onclick=()=>mm.classList.add('show');mm.querySelector('.close').onclick=()=>mm.classList.remove('show');mm.onclick=e=>{if(e.target===mm)mm.classList.remove('show')}}
const todos=document.querySelectorAll('.todo');todos.forEach(x=>{const k=TODO+'_'+x.dataset.k;if(localStorage.getItem(k)==='1')x.checked=true;x.onchange=()=>{localStorage.setItem(k,x.checked?'1':'0');update()}});update();});